#+ summary: Given a clinical measure, what rows reference it

PREFIX ccf: <http://purl.org/ccf/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wpp: <https://purl.wholepersonphysiome.org/schema/wpp#>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>

PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX WPP: <https://purl.wholepersonphysiome.org/collection/wpp>

SELECT DISTINCT ?table ?row_index ?measure_label ?measure_iri
FROM WPP:
WHERE {
  # VALUES (?measure_label) {
  #   ("Core stability assessment"^^xsd:string)
  #   ("histamine levels"^^xsd:string)
  # }

  ?record a wpp:Record ;
    wpp:record_source ?source ;
    wpp:record_number ?row_index ;
    wpp:clinical_measure_field|wpp:signal_field [
      a wpp:ClinicalMeasureField ;
      # skos:prefLabel ?measure_pref_label ;
      skos:prefLabel ?measure_label ;
      wpp:source_concept ?measure_iri ;
    ] ;
  .

  BIND(REPLACE(REPLACE(STR(?source), 'https://purl.wholepersonphysiome.org/wpp/', ''), '-', ' ') as ?table)
  # FILTER(LCASE(?measure_label) = LCASE(?measure_pref_label))
}
ORDER BY ?measure_label ?table ?row_index
