#+ summary: What processes are associated with effector

PREFIX ccf: <http://purl.org/ccf/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wpp: <https://purl.wholepersonphysiome.org/schema/wpp#>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>

PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX WPP: <https://purl.wholepersonphysiome.org/collection/wpp>

SELECT DISTINCT ?table ?row_index ?effector_id ?effector_label ?process
FROM WPP:
WHERE {
  # VALUES (?iri) {
  #   (UBERON:0001155)
  # }

  ?record a wpp:Record ;
    wpp:record_source ?source ;
    wpp:record_number ?row_index ;
    wpp:effector_field|wpp:effector_location_field [
      wpp:source_concept ?iri ;
    ] ;
    wpp:process_field ?process ;
  .

  BIND(REPLACE(REPLACE(STR(?source), 'https://purl.wholepersonphysiome.org/wpp/', ''), '-', ' ') as ?table)
  BIND(REPLACE(STR(?iri), STR(UBERON:), 'UBERON:') as ?effector_id)
  ?iri rdfs:label ?effector_label .
}
ORDER BY ?process ?table ?row_index
