#+ summary: WPP time scales in tables with imperfect cleaning

PREFIX ccf: <http://purl.org/ccf/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wpp: <https://purl.wholepersonphysiome.org/schema/wpp#>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>

PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX WPP: <https://purl.wholepersonphysiome.org/collection/wpp>

SELECT ?table ?time_scale ?effector_scale (COUNT(DISTINCT ?process) as ?process_count) 
  (GROUP_CONCAT(DISTINCT ?time_scale_clean;SEPARATOR='|') as ?raw_time_scales)
  (GROUP_CONCAT(DISTINCT ?process;SEPARATOR='|') as ?processes)

WITH {
  SELECT * 
  WHERE {
    GRAPH WPP: {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        wpp:time_scale_field ?raw_time_scale ;
        wpp:effector_scale_field ?raw_effector_scale ;
        wpp:process_field ?process ;
      ] .
    }

    # TODO: Update these values at the source
    BIND(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LCASE(?raw_time_scale), '\\(.*\\)\\s*', ''), '^\\s+|\\s+$', ''), ', ', '-'), '–', '-'), ' to ', '-') as ?time_scale_clean)
    # TODO: Update these values at the source
    BIND(CONCAT(UCASE(SUBSTR(?raw_effector_scale, 1, 1)), LCASE(SUBSTR(?raw_effector_scale, 2))) as ?effector_scale)
    BIND(REPLACE(STR(?source), 'https://purl.wholepersonphysiome.org/wpp/', '') as ?table)
  }

} AS %table

WHERE {
  {
    INCLUDE %table
    FILTER(?time_scale_clean = 'milliseconds' || STRBEFORE(?time_scale_clean, '-') = 'milliseconds' || STRAFTER(?time_scale_clean, '-') = 'milliseconds')
    BIND('<1 second' as ?time_scale)
  }
  UNION
  {
    INCLUDE %table
    FILTER(?time_scale_clean = 'breath-to-breath' || ?time_scale_clean = 'seconds' || STRBEFORE(?time_scale_clean, '-') = 'seconds' || STRAFTER(?time_scale_clean, '-') = 'seconds')
    BIND('1s - < 1min' as ?time_scale)
  }
  UNION
  {
    INCLUDE %table
    FILTER(?time_scale_clean = 'minutes' || STRBEFORE(?time_scale_clean, '-') = 'minutes' || STRAFTER(?time_scale_clean, '-') = 'minutes')
    BIND('1min - < 1hr' as ?time_scale)
  }
  UNION
  {
    INCLUDE %table
    FILTER(?time_scale_clean = 'hours' || STRBEFORE(?time_scale_clean, '-') = 'hours' || STRAFTER(?time_scale_clean, '-') = 'hours')
    BIND('1hr - < 1day' as ?time_scale)
  }
  UNION
  {
    INCLUDE %table
    FILTER(?time_scale_clean = 'days' || STRBEFORE(?time_scale_clean, '-') = 'days' || STRAFTER(?time_scale_clean, '-') = 'days')
    BIND('1day - < 1week' as ?time_scale)
  }
  UNION
  {
    INCLUDE %table
    FILTER(?time_scale_clean = 'weeks' || STRBEFORE(?time_scale_clean, '-') = 'weeks' || STRAFTER(?time_scale_clean, '-') = 'weeks'
      || ?time_scale_clean = 'months' || STRBEFORE(?time_scale_clean, '-') = 'months' || STRAFTER(?time_scale_clean, '-') = 'months')
    BIND('1week - < 1year' as ?time_scale)
  }
  UNION
  {
    INCLUDE %table
    FILTER(?time_scale_clean = 'years' || STRBEFORE(?time_scale_clean, '-') = 'years' || STRAFTER(?time_scale_clean, '-') = 'years')
    BIND('1year or longer' as ?time_scale)
  }
}
GROUP BY ?table ?time_scale ?effector_scale
ORDER BY ?table ?time_scale ?effector_scale
