#+ summary: CL IDs in ASCT+B that are not in WPP tables

PREFIX ccf: <http://purl.org/ccf/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wpp: <https://purl.wholepersonphysiome.org/schema/wpp#>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>

PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX WPP: <https://purl.wholepersonphysiome.org/collection/wpp>

SELECT ?id (SAMPLE(?label) as ?label) (GROUP_CONCAT(DISTINCT ?table;SEPARATOR='|') as ?asctb_tables)
WHERE {
  hint:Query hint:analytic "true" .

  GRAPH HRA: {
    {
      ?record a ccf:AsctbRecord ;
        ccf:cell_type [
          ccf:source_concept ?iri 
        ] .
    }
    UNION
    {
      ?iri ccf:ccf_asctb_type ?asctb_type .
      FILTER(STR(?asctb_type) = 'CT')
    }
    
    ?iri rdfs:label ?label .
    BIND(REPLACE(STR(?iri), STR(CL:), 'CL:') as ?id)
    BIND(STRBEFORE(REPLACE(STRBEFORE(STR(?record), '#'), 'https://purl.humanatlas.io/asct-b/', ''), '/') as ?table)

    FILTER NOT EXISTS {
      SELECT DISTINCT ?iri
      WHERE {
        GRAPH WPP: {
          [
            a wpp:Record ;
            wpp:record_source ?source ;
            ?field [
              wpp:source_concept ?iri ;
            ] ;
          ] .
          FILTER(STRSTARTS(STR(?iri), STR(CL:)))
          hint:SubQuery hint:runOnce true .
        }
      }
    }
  }
}
GROUP BY ?id
ORDER BY ?id
