#+ summary: WPP table information

PREFIX ccf: <http://purl.org/ccf/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wpp: <https://purl.wholepersonphysiome.org/schema/wpp#>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>

PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX WPP: <https://purl.wholepersonphysiome.org/collection/wpp>

SELECT DISTINCT ?label (?source as ?url) ?uniqueOrgans ?uniqueAS (COALESCE(?uniqueFTU, 0) as ?uniqueFTU) ?uniqueCT (0 as ?uniqueB)
  ?uniqueProcesses ?spatialScales ?temporalScales
FROM WPP:
WHERE {
  [] a wpp:Record ; wpp:record_source ?source .
  BIND(REPLACE(REPLACE(STR(?source), 'https://purl.wholepersonphysiome.org/wpp/', ''), '-', ' ') as ?label)

  OPTIONAL {
    SELECT ?source (COUNT(DISTINCT ?organ) as ?uniqueOrgans)
    WHERE {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        ?field [
          wpp:source_concept ?iri ;
        ] ;
      ] .

      GRAPH HRA: {
        ?hra_record a ccf:AsctbRecord ;
          ?hra_field [
            ccf:source_concept ?iri 
          ] .

        BIND(STRBEFORE(REPLACE(STRBEFORE(STR(?hra_record), '#'), 'https://purl.humanatlas.io/asct-b/', ''), '/') as ?organ)
      }
    }
    GROUP BY ?source
  }

  OPTIONAL {
    SELECT ?source (COUNT(DISTINCT ?iri) as ?uniqueAS)
    WHERE {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        ?field [
          wpp:source_concept ?iri ;
        ] ;
      ] .

      FILTER(STRSTARTS(STR(?iri), STR(UBERON:)))
    }
    GROUP BY ?source
  }

  OPTIONAL {
    SELECT ?source (COUNT(DISTINCT ?iri) as ?uniqueCT)
    WHERE {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        ?field [
          wpp:source_concept ?iri ;
        ] ;
      ] .

      FILTER(STRSTARTS(STR(?iri), STR(CL:)))
    }
    GROUP BY ?source
  }

  OPTIONAL {
    SELECT ?source (COUNT(DISTINCT ?iri) as ?uniqueFTU)
    WHERE {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        ?field [
          wpp:source_concept ?iri ;
        ] ;
      ] .

      GRAPH HRA: {
        {
          [
            a ccf:FtuIllustration ;
            ccf:representation_of ?iri ;
          ] .
        }
        UNION
        {
          [
            a ccf:AsctbRecord ;
            ccf:ftu_types [
              ccf:source_concept ?iri 
            ];
          ] .
        }
        ?iri rdfs:label ?label .
      }
    }
    GROUP BY ?source
  }

  OPTIONAL {
    SELECT ?source (COUNT(DISTINCT ?iri) as ?uniqueProcesses)
    WHERE {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        wpp:process_field ?iri ;
      ] .
    }
    GROUP BY ?source
  }

  OPTIONAL {
    SELECT ?source (COUNT(DISTINCT ?iri) as ?spatialScales)
    WHERE {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        wpp:effector_scale_field ?iri ;
      ] .
    }
    GROUP BY ?source
  }

  OPTIONAL {
    SELECT ?source (COUNT(DISTINCT ?iri) as ?temporalScales)
    WHERE {
      [
        a wpp:Record ;
        wpp:record_source ?source ;
        wpp:time_scale_field ?iri ;
      ] .
    }
    GROUP BY ?source
  }
}
